<?php
/**
 * The configuration file the drop-in reads.
 *
 * @package BricksCache
 */

namespace BricksCache;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The drop-in runs with no database and no plugins, so everything it needs to
 * decide is flattened into one PHP file that returns an array. This class is
 * the only writer of that file: it is rebuilt whenever the settings, the
 * WooCommerce pages or the plugin version change.
 */
final class Config {

	/**
	 * Settings instance.
	 */
	private Settings $settings;

	/**
	 * @param Settings $settings Settings instance.
	 */
	public function __construct( Settings $settings ) {
		$this->settings = $settings;
	}

	/**
	 * Absolute path of the generated config file.
	 */
	public static function file(): string {
		return Filesystem::dir( 'config' ) . '/config.php';
	}

	/**
	 * Build the array the drop-in will read.
	 *
	 * @return array<string,mixed>
	 */
	public function build(): array {
		$config = [
			'version'            => BRICKS_CACHE_VERSION,
			'dropin_version'     => BRICKS_CACHE_DROPIN_VERSION,
			'generated'          => time(),
			'enabled'            => $this->settings->on( 'page_cache.enabled' ),
			'ttl'                => (int) $this->settings->get( 'page_cache.ttl', 43200 ),
			'gzip'               => $this->settings->on( 'page_cache.gzip' ),
			'mobile_variant'     => $this->settings->on( 'page_cache.mobile_variant' ),
			'page_dir'           => Filesystem::dir( 'page' ),
			'plugin_dir'         => untrailingslashit( BRICKS_CACHE_PATH ),
			'home_path'          => $this->home_path(),
			'ignored_query_args' => (array) $this->settings->get( 'page_cache.ignored_query_args', [] ),
			'cached_query_args'  => (array) $this->settings->get( 'page_cache.cached_query_args', [] ),
			'excluded_paths'     => $this->excluded_paths(),
			'excluded_cookies'   => (array) $this->settings->get( 'exclusions.cookies', [] ),
			'excluded_agents'    => (array) $this->settings->get( 'exclusions.user_agents', [] ),
			'variant_cookies'    => [],
			'debug_headers'      => defined( 'WP_DEBUG' ) && WP_DEBUG,
		];

		/**
		 * Filter the configuration handed to the drop-in. Compatibility layers
		 * add their own exclusions here.
		 *
		 * @param array<string,mixed> $config Configuration.
		 */
		return (array) apply_filters( 'bricks_cache_config', $config );
	}

	/**
	 * Write the config file. Returns false when the disk refused it, which is
	 * a hard failure: an outdated config means the drop-in serves by old rules.
	 */
	public function write(): bool {
		$config = $this->build();

		$body = "<?php\n"
			. "/**\n * Generated by Bricks Cache. Do not edit: it is rebuilt on every save.\n */\n\n"
			. 'if ( ! defined( \'ABSPATH\' ) ) { return []; }' . "\n\n"
			. 'return ' . var_export( $config, true ) . ";\n"; // phpcs:ignore WordPress.PHP.DevelopmentFunctions

		return Filesystem::write( self::file(), $body );
	}

	/**
	 * Read back what the drop-in would read, for diagnostics.
	 *
	 * @return array<string,mixed>
	 */
	public static function read(): array {
		$file = self::file();

		if ( ! is_readable( $file ) ) {
			return [];
		}

		$config = include $file;

		return is_array( $config ) ? $config : [];
	}

	/**
	 * Path part of the site home, so a WordPress in a subdirectory still maps
	 * URLs correctly.
	 */
	private function home_path(): string {
		$path = (string) wp_parse_url( home_url( '/' ), PHP_URL_PATH );

		return '' === $path ? '/' : $path;
	}

	/**
	 * Paths that must never be cached on this particular site: the shop pages
	 * as they are actually configured, plus whatever the user excluded.
	 *
	 * @return string[]
	 */
	private function excluded_paths(): array {
		$paths = [];

		foreach ( (array) $this->settings->get( 'exclusions.urls', [] ) as $pattern ) {
			$pattern = trim( (string) $pattern );

			if ( '' !== $pattern ) {
				$paths[] = $pattern;
			}
		}

		/**
		 * Filter the never-cached paths. WooCommerce and the shop plugins add
		 * their own pages through this filter.
		 *
		 * @param string[] $paths Path patterns, may contain *.
		 */
		$paths = (array) apply_filters( 'bricks_cache_excluded_paths', $paths );

		return array_values( array_unique( array_filter( array_map( 'strval', $paths ) ) ) );
	}
}
